SRC=src
PDFLATEX=pdflatex
FILENAME=prezentacja

all:
	${PDFLATEX} ${SRC}/prezentacja.tex 

clean: 
	rm  ${FILENAME}.aux \
		${FILENAME}.log \
		${FILENAME}.log \
		${FILENAME}.out \
		${FILENAME}.snm \
		${FILENAME}.aux \
		${FILENAME}.nav \
		${FILENAME}.toc \

